### ISSUE TITLE
add option to use ctrl instead

### ISSUE THREAD

**Issue by mark-hahn** [geoffthibeau/simple-drag-drop-text#1]

**Comment by bewam** [comment]
Thanks for your work, it's very useful when you come from other editors, because most have. 

The ctrl key in most (almost all) editors is used to copy-paste (keep original selection), the pointer become one with the sign +. It would be nice to use the key this way and keep the standard actual cut-paste behavior as it was first implemented.

**Comment by mark-hahn** [comment]
Thanks.  I'll get to this asap.

**Comment by jakeboone02** [comment]
Looks like #6 closes this issue, but I had a question:  Why is `alt` the default?  I can't think of an instance in any other program or OS where `ctrl`/`cmd` is not the "copy-instead-of-move" modifier.  #6 makes this a moot point, I was just curious.

**Comment by mark-hahn** [comment]
> where ctrl/cmd is not the "copy-instead-of-move" modifier.

I agree.

> Why is alt the default?

I don't remember for sure.  I think there was some conflict on my setup.  I
couldn't even test it.  Feel free to try to change it.  It should be a
trivial change.

**Comment by jakeboone02** [comment]
OK, will do.  I've never created an Atom extension before, so I have a quick question.

If I make this change:

``` diff
 class SimpleDragDropText
   config:
     copyKey:
       type: 'string'
-      default: 'alt'
+      default: 'ctrl'
       description: 'Select key for copy action'
       enum: ['alt', 'ctrl', 'meta']
```

Will the change only affect new users, or will existing users have their settings changed when they upgrade?

**Comment by mark-hahn** [comment]
The code you are showing me allows you to change the key in options.  I
didn't remember I had that in there.  Have you tried changing the setting?

Your change would only change the default setting.  Why would you care?

**Comment by jakeboone02** [comment]
That answers the question.  I would care because I wouldn't want to change all users' key bindings when they update the extension.  They can change the option if they want, as you said, but an update shouldn't force the change on everyone.

I'll put a PR in for the change I showed above. Thanks.

**Comment by mark-hahn** [comment]
> an update shouldn't force the change on everyone.

The settings don't change on an update.

**Comment by jakeboone02** [comment]
That answers the question I had. Thanks.

**Comment by ADTC** [comment]
Thanks for this wonderful package adding a much-needed basic feature to Atom! :smiley: And I really want to thank you for making sure I can change the modifier key to Ctrl if I want to. Before installing the package, I didn't know I can (since the readme makes no mention of Ctrl), and I was looking for another package which will surely let me do it. But lucky for you, there was no other package. :laughing: 

I back this PR and hope it can be merged. The Ctrl key is indeed the correct key that _"mimics the standard behavior of many other editors"_ (as quoted from the home page). The standard behavior is to hold Ctrl key while dragging to copy the dragged text. I have honestly never heard of any editor using Alt by default to do the same. So I also agree that Ctrl key should be the default.

The changelog shown during update should mention _"Default changed to Ctrl. If you're updating, your current setting will not be changed automatically. If you want to change it, see the package settings."_

BTW, what is "meta" modifier?

**Comment by bewam** [comment]
On PC (Windows OR Linux), the Alt is mainly used as shortcut for navigation or to type the Alt-codes on Windows. A menu is called by it's underlined character. The Meta is the "Windows® key" which is used mostly for OS operations, as exemple-the only I know- meta-R on Windows is Run window. The other special key on classical keyboards is the "menu key" for the popup menu.

**Comment by geoffthibeau** [comment]
Thanks, @jakeboone02. Your pull request was merged this morning.

**Comment by ADTC** [comment]
Could you also enhance the Readme? It should change the mentions of default modifier from "Alt" to "Ctrl" and then add a mention for the ability to change it to Alt or Meta in the package settings.

Also make a mention of what "meta" really means (in the Readme, not here).

**Comment by geoffthibeau** [comment]
@ADTC Is the existing README not satisfactory? I included super/Windows/command as a description of meta.

**Comment by ADTC** [comment]
@geoffthibeau so sorry. I didn't notice that you had already updated the Readme in b642225 😨 😄

**Comment by geoffthibeau** [comment]
@ADTC No worries.
