### ISSUE TITLE
cursor when dragging and hovering selection

### ISSUE THREAD

**Issue by robsonsobral** [geoffthibeau/simple-drag-drop-text#10]
Hi!

Thanks for the package.

Is it possible, please, to change the cursor when dragging and hovering the selection?

**Comment by ryanjkelly** [comment]
+1

**Comment by mark-hahn** [comment]
Yes.  I will be working on this package soon and I'll add it.

**Comment by Sogl** [comment]
+1 

Need it like in Sublime Text:
![4](https://cloud.githubusercontent.com/assets/7556290/11953940/fa55d816-a8ef-11e5-9c72-7cc15eb20b8f.gif)

**Comment by mark-hahn** [comment]
What is the difference you are asking for?

**Comment by Sogl** [comment]
> What is the difference you are asking for?

No difference. Just an example.

**Comment by mark-hahn** [comment]
I mean, why did you post this issue?  I haven't been using drag-drop and I
don't remember what it looks like.

**Comment by mark-hahn** [comment]
Never mind.  When I get a chance I'll fire it up and compare the two.

**Comment by Sogl** [comment]
> I mean, why did you post this issue?
1. Issue starter is `robsonsobral`, not me. But for me this feature is missed too.
2. I post gif from ST for all, not only for you...and just for example. I think you know very well how it looks like. :smirk: 

> When I get a chance I'll fire it up and compare the two.

:+1: 

Thank you for your attention.

**Comment by axefrog** [comment]
@mark-hahn The conversation is clearly worded confusingly, though I am 99% sure that what was intended is the same as what I come here to report as an issue. Instead, I'll add what I was going to say here, rather than creating a new issue.

The normal experience for dragging text is as follows:
- When text is selected, hovering over the selection changes the cursor to a pointer/arrow
- Clicking and dragging a selection changes the cursor to an arrow/dragging icon
- When moving the cursor to find a drop target/location, the only visual variance is that of the position of the insertion glyph indicating where the text will be dropped if the mouse button is released.

In contrast, the current experience is as follows:
- When hovering over a selection, the i-bar (text selection cursor) is still displayed, which sort of suggests that the editor doesn't recognise the significance of the fact that the user has selected a range of text.
- When dragging a block of text quickly, I frequently see briefly-flickering ranges of selected text as though my movement of the cursor is causing erroneous selection while I'm locating the drop position.

**Comment by axefrog** [comment]
I've created a short animation to illustrate my previous message and to help contrast the two experiences:

![atom-mark-hahn-simple-drag-drop-text-issue-10](https://cloud.githubusercontent.com/assets/298883/14057929/075b754c-f35b-11e5-8a24-de34df843a11.gif)

**Comment by enoversum** [comment]
Yeah, that confused me, too, when I just installed your package. Would like it as in Sublime as well :smile: .

**Comment by ADTC** [comment]
I want this too. Those animation examples are neat, but they missed out one thing: When the copy modifier key is held down, the "arrow with box" pointer has an additional [+] sign to indicate the copy operation.

PS: It doesn't look like the current Atom API supports changing mouse pointer at all. The term "cursor" refers to the **text caret** in the API docs.

**Comment by ADTC** [comment]
I think it should be possible using the `cursor` CSS property put in some classes, and then _somehow_ have the appropriate class applied to the editor pane while dragging or hovering, etc.

Hover: `cursor: default;` or `cursor: grab;`
Move: `cursor: alias;` or `cursor: move;` or `cursor: grabbing;`
Copy: `cursor: copy;`
Normal: unset or reset to `cursor: text;`

I looked at the API docs and another package that uses CSS styles (not cursor though) and couldn't figure out how that would work. The docs and the system are so confusing...

**Comment by Sogl** [comment]
@geoffthibeau As a new repository owner, do you have time and pleasure to resolve this enhancement?

**Comment by geoffthibeau** [comment]
@Sogl Yep. I looked through the issues today and hope to resolve them soon. Atom is my daily editor so trying to give back in a small way.

**Comment by rondonjon** [comment]
Thanks for taking over, @geoffthibeau. Any news on this? Apparently one of the most-wanted features.

**Comment by kaiyoma** [comment]
Wow, no updates in a year and a half. It's pretty bothersome that the mouse cursor doesn't change to the default when hovering. Any chance on this getting fixed soon?

**Comment by Lotharyx** [comment]
I humbly suggest this issue not be considered "closed" yet for a few reasons:

1) The standard arror cursor isn't really the "right" cursor to use during drag
2) The cursor still shows up as I-beam before dragging starts (possibly out of scope for this module)
3) The issue of confusing visual effects reported by @axefrog are still in evidence

The situation is certainly improved by the recent commit (a423ea), but not "closed" in my opinion.

PS: I hate to complain and not contribute, but unfortunately right now I am swamped with other pursuits.  Hopefully some day I'll have some free time to contribute to this project myself.
